### PR TITLE
Use version 4.x

### PR DESCRIPTION
**Pull request by balpurewal**
# Pull Request Template

## 📲 What

Use version 4.x

## 🤔 Why

Otherwise we are pinned against "3.108.x" and we are forced to use a older version.

### CODE REVIEW

**Comment by ElvenSpellmaker** [comment]
Have you considered 4.x?

**Comment by balpurewal** [comment]
Currently can't use "~> 4.0" because we are using this module alongside of stacks-terraform modules which currently have "~> 3.0" so it will fail to resolve a version. 
Probably could use "~> 3" which means it will use v3.116.0 if used with other stacks-terraform modules and then a 4 version if not.

**Comment by ElvenSpellmaker** [comment]
Is it possible to bump the dependent module too?

**Comment by balpurewal** [comment]
I will try, let me check the impact

**Review by ElvenSpellmaker — APPROVED** [review]

**Pull request merged**
